### Label Encode Categorical Data

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing as prep

In [2]:
# explore and handle data

train_df = pd.read_csv('./data/train.csv')
test_df = pd.read_csv('./data/test.csv')

In [3]:
test_df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [4]:
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
# add test df a survived cloumn

test_df['Survived'] = 0

In [6]:
test_df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Survived  
0  34.5      0      0   330911   7.8292   NaN        Q         0  
1  47.0      1      0   363272   7.0000   NaN        S         0  
2  62.0      0      0   240276   9.6875   NaN        Q         0  
3  27.0      0      0   315154   8.6625   NaN        S         0  
4  22.0      1      1  3101298  12.2875   NaN        S         0

In [7]:
# concat train and test sets

concat = train_df.append(test_df, ignore_index=True)

In [8]:
concat.head()

Age Cabin Embarked     Fare  \
0  22.0   NaN        S   7.2500   
1  38.0   C85        C  71.2833   
2  26.0   NaN        S   7.9250   
3  35.0  C123        S  53.1000   
4  35.0   NaN        S   8.0500   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   

   Pclass     Sex  SibSp  Survived            Ticket  
0       3    male      1         0         A/5 21171  
1       1  female      1         1          PC 17599  
2       3  female      0         1  STON/O2. 3101282  
3       1  female      1         1            113803  
4       3    male      0         0            373450

In [9]:
print(train_df.shape)
print(test_df.shape)
print(concat.shape)

(891, 12)
(418, 12)
(1309, 12)


In [10]:
train_df.Embarked[881:]

881    S
882    S
883    S
884    S
885    Q
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, dtype: object

In [11]:
test_df.Embarked[:10]

0    Q
1    S
2    Q
3    S
4    S
5    S
6    Q
7    S
8    C
9    S
Name: Embarked, dtype: object

In [12]:
concat.Embarked[881:901]

881    S
882    S
883    S
884    S
885    Q
886    S
887    S
888    S
889    C
890    Q
891    Q
892    S
893    Q
894    S
895    S
896    S
897    Q
898    S
899    C
900    S
Name: Embarked, dtype: object

In [13]:
concat.Survived[881:901]

881    0
882    0
883    0
884    0
885    0
886    0
887    1
888    0
889    1
890    0
891    0
892    0
893    0
894    0
895    0
896    0
897    0
898    0
899    0
900    0
Name: Survived, dtype: int64

In [14]:
concat.Sex.head(10)

0      male
1    female
2    female
3    female
4      male
5      male
6      male
7      male
8    female
9    female
Name: Sex, dtype: object

In [15]:
concat.Sex.unique()

array(['male', 'female'], dtype=object)

In [16]:
le = prep.LabelEncoder()

In [17]:
le.fit(concat.Sex)

LabelEncoder()

In [18]:
le.classes_

array(['female', 'male'], dtype=object)

In [19]:
Sex_le = le.transform(concat.Sex)

Sex_le[0:10]

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0])

In [20]:
concat_le = concat.copy()

concat_le.head()

Age Cabin Embarked     Fare  \
0  22.0   NaN        S   7.2500   
1  38.0   C85        C  71.2833   
2  26.0   NaN        S   7.9250   
3  35.0  C123        S  53.1000   
4  35.0   NaN        S   8.0500   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   

   Pclass     Sex  SibSp  Survived            Ticket  
0       3    male      1         0         A/5 21171  
1       1  female      1         1          PC 17599  
2       3  female      0         1  STON/O2. 3101282  
3       1  female      1         1            113803  
4       3    male      0         0            373450

In [21]:
concat_le.Sex = Sex_le

concat_le.head()

Age Cabin Embarked     Fare  \
0  22.0   NaN        S   7.2500   
1  38.0   C85        C  71.2833   
2  26.0   NaN        S   7.9250   
3  35.0  C123        S  53.1000   
4  35.0   NaN        S   8.0500   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   

   Pclass  Sex  SibSp  Survived            Ticket  
0       3    1      1         0         A/5 21171  
1       1    0      1         1          PC 17599  
2       3    0      0         1  STON/O2. 3101282  
3       1    0      1         1            113803  
4       3    1      0         0            373450

In [22]:
concat_le.dtypes

Age            float64
Cabin           object
Embarked        object
Fare           float64
Name            object
Parch            int64
PassengerId      int64
Pclass           int64
Sex              int64
SibSp            int64
Survived         int64
Ticket          object
dtype: object

In [23]:
print(concat.Survived.unique())
print(concat.Pclass.unique())
print(concat.Sex.unique())
print(concat.SibSp.unique())
print(concat.Parch.unique())
print(concat.Embarked.unique())

[0 1]
[3 1 2]
['male' 'female']
[1 0 3 4 2 5 8]
[0 1 2 5 3 4 6 9]
['S' 'C' 'Q' nan]


In [24]:
embarked = concat['Embarked'].fillna('0')

In [25]:
embarked.unique()

array(['S', 'C', 'Q', '0'], dtype=object)

In [26]:
le.fit(embarked)

LabelEncoder()

In [27]:
le.classes_

array(['0', 'C', 'Q', 'S'], dtype=object)

In [28]:
embarked = le.transform(embarked)

In [29]:
embarked[:10]

array([3, 1, 3, 3, 3, 2, 3, 3, 3, 1])

In [30]:
concat_le.Embarked = embarked

In [31]:
concat_le.head(10)

Age Cabin  Embarked     Fare  \
0  22.0   NaN         3   7.2500   
1  38.0   C85         1  71.2833   
2  26.0   NaN         3   7.9250   
3  35.0  C123         3  53.1000   
4  35.0   NaN         3   8.0500   
5   NaN   NaN         2   8.4583   
6  54.0   E46         3  51.8625   
7   2.0   NaN         3  21.0750   
8  27.0   NaN         3  11.1333   
9  14.0   NaN         1  30.0708   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   
5                                   Moran, Mr. James      0            6   
6                            McCarthy, Mr. Timothy J      0            7   
7                     Palsson, Master. Gosta Leonard      1            8   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)      2            9   
9                Nasser, Mrs. Nicholas (Adele Achem)      0           10   

   Pclass  Sex  SibSp  Survived            Ticket  
0       3    1      1         0         A/5 21171  
1       1    0      1         1          PC 17599  
2       3    0      0         1  STON/O2. 3101282  
3       1    0      1         1            113803  
4       3    1      0         0            373450  
5       3    1      0         0            330877  
6       1    1      0         0             17463  
7       3    1      3         0            349909  
8       3    0      0         1            347742  
9       2    0      1         1            237736

In [32]:
train_le = concat_le.iloc[:892].copy()
test_le = concat_le.iloc[892:].copy()

In [33]:
train_le[880:]

Age Cabin  Embarked     Fare  \
880  25.0   NaN         3  26.0000   
881  33.0   NaN         3   7.8958   
882  22.0   NaN         3  10.5167   
883  28.0   NaN         3  10.5000   
884  25.0   NaN         3   7.0500   
885  39.0   NaN         2  29.1250   
886  27.0   NaN         3  13.0000   
887  19.0   B42         3  30.0000   
888   NaN   NaN         3  23.4500   
889  26.0  C148         1  30.0000   
890  32.0   NaN         2   7.7500   
891  34.5   NaN         2   7.8292   

                                             Name  Parch  PassengerId  Pclass  \
880  Shelley, Mrs. William (Imanita Parrish Hall)      1          881       2   
881                            Markun, Mr. Johann      0          882       3   
882                  Dahlberg, Miss. Gerda Ulrika      0          883       3   
883                 Banfield, Mr. Frederick James      0          884       2   
884                        Sutehall, Mr. Henry Jr      0          885       3   
885          Rice, Mrs. William (Margaret Norton)      5          886       3   
886                         Montvila, Rev. Juozas      0          887       2   
887                  Graham, Miss. Margaret Edith      0          888       1   
888      Johnston, Miss. Catherine Helen "Carrie"      2          889       3   
889                         Behr, Mr. Karl Howell      0          890       1   
890                           Dooley, Mr. Patrick      0          891       3   
891                              Kelly, Mr. James      0          892       3   

     Sex  SibSp  Survived            Ticket  
880    0      0         1            230433  
881    1      0         0            349257  
882    0      0         0              7552  
883    1      0         0  C.A./SOTON 34068  
884    1      0         0   SOTON/OQ 392076  
885    0      0         0            382652  
886    1      0         0            211536  
887    0      0         1            112053  
888    0      1         0        W./C. 6607  
889    1      0         1            111369  
890    1      0         0            370376  
891    1      0         0            330911

In [34]:
test_le[:10]

Age Cabin  Embarked     Fare  \
892  47.0   NaN         3   7.0000   
893  62.0   NaN         2   9.6875   
894  27.0   NaN         3   8.6625   
895  22.0   NaN         3  12.2875   
896  14.0   NaN         3   9.2250   
897  30.0   NaN         2   7.6292   
898  26.0   NaN         3  29.0000   
899  18.0   NaN         1   7.2292   
900  21.0   NaN         3  24.1500   
901   NaN   NaN         3   7.8958   

                                             Name  Parch  PassengerId  Pclass  \
892              Wilkes, Mrs. James (Ellen Needs)      0          893       3   
893                     Myles, Mr. Thomas Francis      0          894       2   
894                              Wirz, Mr. Albert      0          895       3   
895  Hirvonen, Mrs. Alexander (Helga E Lindqvist)      1          896       3   
896                    Svensson, Mr. Johan Cervin      0          897       3   
897                          Connolly, Miss. Kate      0          898       3   
898                  Caldwell, Mr. Albert Francis      1          899       2   
899     Abrahim, Mrs. Joseph (Sophie Halaut Easu)      0          900       3   
900                       Davies, Mr. John Samuel      0          901       3   
901                              Ilieff, Mr. Ylio      0          902       3   

     Sex  SibSp  Survived     Ticket  
892    0      1         0     363272  
893    1      0         0     240276  
894    1      0         0     315154  
895    0      1         0    3101298  
896    1      0         0       7538  
897    0      0         0     330972  
898    1      1         0     248738  
899    0      0         0       2657  
900    1      2         0  A/4 48871  
901    1      0         0     349220

In [35]:
train_le.to_csv('./data/train_le.csv')
test_le.to_csv('./data/test_le.csv')

In [36]:
%ls data

gender_submission.csv  test.csv  test_le.csv  train.csv  train_le.csv
